# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'h:\CME495\desktop-app\homebrew-controller\brewConfirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_brewConfirmationDialog(object):
    def setupUi(self, brewConfirmationDialog):
        brewConfirmationDialog.setObjectName("brewConfirmationDialog")
        brewConfirmationDialog.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("h:\\CME495\\desktop-app\\homebrew-controller\\../../beerIcone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        brewConfirmationDialog.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtWidgets.QWidget(brewConfirmationDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 90, 381, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ferm1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ferm1.sizePolicy().hasHeightForWidth())
        self.ferm1.setSizePolicy(sizePolicy)
        self.ferm1.setChecked(True)
        self.ferm1.setObjectName("ferm1")
        self.horizontalLayout.addWidget(self.ferm1)
        self.ferm2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ferm2.sizePolicy().hasHeightForWidth())
        self.ferm2.setSizePolicy(sizePolicy)
        self.ferm2.setObjectName("ferm2")
        self.horizontalLayout.addWidget(self.ferm2)
        self.ferm3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ferm3.sizePolicy().hasHeightForWidth())
        self.ferm3.setSizePolicy(sizePolicy)
        self.ferm3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ferm3.setObjectName("ferm3")
        self.horizontalLayout.addWidget(self.ferm3)
        self.sendButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.sendButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout.addWidget(self.sendButton)
        self.label_2 = QtWidgets.QLabel(brewConfirmationDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(brewConfirmationDialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(120, 210, 160, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.yesButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.yesButton.setObjectName("yesButton")
        self.horizontalLayout_2.addWidget(self.yesButton)
        self.statusLabel = QtWidgets.QLabel(brewConfirmationDialog)
        self.statusLabel.setGeometry(QtCore.QRect(110, 170, 171, 41))
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")

        self.retranslateUi(brewConfirmationDialog)
        QtCore.QMetaObject.connectSlotsByName(brewConfirmationDialog)

    def retranslateUi(self, brewConfirmationDialog):
        _translate = QtCore.QCoreApplication.translate
        brewConfirmationDialog.setWindowTitle(_translate("brewConfirmationDialog", "Ready to brew?"))
        self.ferm1.setText(_translate("brewConfirmationDialog", "Fermentor 1"))
        self.ferm2.setText(_translate("brewConfirmationDialog", "Fermentor 2"))
        self.ferm3.setText(_translate("brewConfirmationDialog", "Fermentor 3"))
        self.sendButton.setText(_translate("brewConfirmationDialog", "Send Data"))
        self.label_2.setText(_translate("brewConfirmationDialog", "Select Fermentor:"))
        self.yesButton.setText(_translate("brewConfirmationDialog", "Done"))
        self.statusLabel.setText(_translate("brewConfirmationDialog", "Waiting to send..."))
