# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'h:\CME495\desktop-app\homebrew-controller\deleteConfirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteConfirmationDialog(object):
    def setupUi(self, DeleteConfirmationDialog):
        DeleteConfirmationDialog.setObjectName("DeleteConfirmationDialog")
        DeleteConfirmationDialog.resize(500, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("h:\\CME495\\desktop-app\\homebrew-controller\\../../beerIcone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DeleteConfirmationDialog.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(DeleteConfirmationDialog)
        self.label.setGeometry(QtCore.QRect(0, 100, 500, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(DeleteConfirmationDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 160, 537, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(150, 0, 150, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yesButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.yesButton.setObjectName("yesButton")
        self.horizontalLayout.addWidget(self.yesButton)
        self.noButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.noButton.setObjectName("noButton")
        self.horizontalLayout.addWidget(self.noButton)

        self.retranslateUi(DeleteConfirmationDialog)
        QtCore.QMetaObject.connectSlotsByName(DeleteConfirmationDialog)

    def retranslateUi(self, DeleteConfirmationDialog):
        _translate = QtCore.QCoreApplication.translate
        DeleteConfirmationDialog.setWindowTitle(_translate("DeleteConfirmationDialog", "Are you sure?"))
        self.label.setText(_translate("DeleteConfirmationDialog", "Are you sure you want to delete ______________ ?"))
        self.yesButton.setText(_translate("DeleteConfirmationDialog", "Yes"))
        self.noButton.setText(_translate("DeleteConfirmationDialog", "No"))
