# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'h:\CME495\desktop-app\homebrew-controller\fileConfirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OverwriteDialog(object):
    def setupUi(self, OverwriteDialog):
        OverwriteDialog.setObjectName("OverwriteDialog")
        OverwriteDialog.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("h:\\CME495\\desktop-app\\homebrew-controller\\../../beerIcone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OverwriteDialog.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(OverwriteDialog)
        self.label.setGeometry(QtCore.QRect(0, 100, 401, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(OverwriteDialog)
        self.label_2.setGeometry(QtCore.QRect(0, 130, 401, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(OverwriteDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 160, 401, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(100, 0, 100, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yesButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.yesButton.setObjectName("yesButton")
        self.horizontalLayout.addWidget(self.yesButton)
        self.noButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.noButton.setObjectName("noButton")
        self.horizontalLayout.addWidget(self.noButton)

        self.retranslateUi(OverwriteDialog)
        QtCore.QMetaObject.connectSlotsByName(OverwriteDialog)

    def retranslateUi(self, OverwriteDialog):
        _translate = QtCore.QCoreApplication.translate
        OverwriteDialog.setWindowTitle(_translate("OverwriteDialog", "Are you sure?"))
        self.label.setText(_translate("OverwriteDialog", "Do you want to overwrite ______________ ?"))
        self.label_2.setText(_translate("OverwriteDialog", "(Clicking \"No\" will create a numbered copy of the file)"))
        self.yesButton.setText(_translate("OverwriteDialog", "Yes"))
        self.noButton.setText(_translate("OverwriteDialog", "No"))
