# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homebrewGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomebrewController(object):
    def setupUi(self, HomebrewController):
        HomebrewController.setObjectName("HomebrewController")
        HomebrewController.resize(1112, 574)
        self.centralwidget = QtWidgets.QWidget(HomebrewController)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 291, 491))
        self.listWidget.setObjectName("listWidget")
        self.label_recipe = QtWidgets.QLabel(self.centralwidget)
        self.label_recipe.setGeometry(QtCore.QRect(10, 10, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_recipe.setFont(font)
        self.label_recipe.setObjectName("label_recipe")
        self.label_preview = QtWidgets.QLabel(self.centralwidget)
        self.label_preview.setGeometry(QtCore.QRect(480, 10, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_preview.setFont(font)
        self.label_preview.setObjectName("label_preview")
        self.recipePreview = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.recipePreview.setGeometry(QtCore.QRect(480, 40, 621, 491))
        self.recipePreview.setObjectName("recipePreview")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(310, 40, 77, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.newRecipeButton = QtWidgets.QPushButton(self.layoutWidget)
        self.newRecipeButton.setObjectName("newRecipeButton")
        self.verticalLayout.addWidget(self.newRecipeButton)
        self.deleteRecipeButton = QtWidgets.QPushButton(self.layoutWidget)
        self.deleteRecipeButton.setObjectName("deleteRecipeButton")
        self.verticalLayout.addWidget(self.deleteRecipeButton)
        self.editRecipeButton = QtWidgets.QPushButton(self.layoutWidget)
        self.editRecipeButton.setObjectName("editRecipeButton")
        self.verticalLayout.addWidget(self.editRecipeButton)
        HomebrewController.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(HomebrewController)
        self.statusbar.setObjectName("statusbar")
        HomebrewController.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(HomebrewController)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 21))
        self.menubar.setObjectName("menubar")
        self.menuRecipes = QtWidgets.QMenu(self.menubar)
        self.menuRecipes.setObjectName("menuRecipes")
        HomebrewController.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(HomebrewController)
        self.actionOpen.setObjectName("actionOpen")
        self.menuRecipes.addAction(self.actionOpen)
        self.menubar.addAction(self.menuRecipes.menuAction())

        self.retranslateUi(HomebrewController)
        QtCore.QMetaObject.connectSlotsByName(HomebrewController)

    def retranslateUi(self, HomebrewController):
        _translate = QtCore.QCoreApplication.translate
        HomebrewController.setWindowTitle(_translate("HomebrewController", "Homebrew Controller"))
        self.listWidget.setSortingEnabled(True)
        self.label_recipe.setText(_translate("HomebrewController", "Recipes"))
        self.label_preview.setText(_translate("HomebrewController", "Preview"))
        self.newRecipeButton.setText(_translate("HomebrewController", "New"))
        self.deleteRecipeButton.setText(_translate("HomebrewController", "Delete"))
        self.editRecipeButton.setText(_translate("HomebrewController", "Edit"))
        self.menuRecipes.setTitle(_translate("HomebrewController", "&File"))
        self.actionOpen.setText(_translate("HomebrewController", "Open"))

