# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'h:\CME495\desktop-app\homebrew-controller\recipeNotes.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_recipeNotes(object):
    def setupUi(self, recipeNotes):
        recipeNotes.setObjectName("recipeNotes")
        recipeNotes.resize(640, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("h:\\CME495\\desktop-app\\homebrew-controller\\../../beerIcone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        recipeNotes.setWindowIcon(icon)
        self.notePad = QtWidgets.QTextEdit(recipeNotes)
        self.notePad.setGeometry(QtCore.QRect(10, 10, 621, 421))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.notePad.setFont(font)
        self.notePad.setObjectName("notePad")
        self.doneButton = QtWidgets.QPushButton(recipeNotes)
        self.doneButton.setGeometry(QtCore.QRect(10, 440, 75, 23))
        self.doneButton.setObjectName("doneButton")
        self.cancelButton = QtWidgets.QPushButton(recipeNotes)
        self.cancelButton.setGeometry(QtCore.QRect(90, 440, 75, 23))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(recipeNotes)
        QtCore.QMetaObject.connectSlotsByName(recipeNotes)

    def retranslateUi(self, recipeNotes):
        _translate = QtCore.QCoreApplication.translate
        recipeNotes.setWindowTitle(_translate("recipeNotes", "Recipe Notes"))
        self.notePad.setPlaceholderText(_translate("recipeNotes", "Write your notes here"))
        self.doneButton.setText(_translate("recipeNotes", "Done"))
        self.cancelButton.setText(_translate("recipeNotes", "Cancel"))
